import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app and simpledoers" />
        <link rel="icon" href="/products.svg" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          <a href="/">SimpleDoers</a>
        </h2>

        <section className={styles.grid}>
          <a href="https://profile.codersrank.io/user/maximilianou/" className={styles.card}>
            <article>
              <h2>Profile &rarr;</h2>
              <p>Find numeric / graph information on hours of coding.</p>
            </article>
          </a>

          <a href="https://github.com/maximilianou" className={styles.card}>
            <article>
              <h2>Learn &rarr;</h2>
              <p>The Source Code by itself.</p>
            </article>
          </a>

        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://simpledoers.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Thanks to {' '}
          <span className={styles.logo}>
            <Image src="/products.svg" alt="SimpleDoers Logo" width={120} height={100} />
          </span>
        </a>
        <a href="http://www.carloacutis.com/" target='_blank'>Venerable Carlo Acutis: A patron of Computer Programmers!</a>
      </footer>
    </div>
  )
}

export default Home
